# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NLK\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\trial_area\modules\otvod\ui\otvodMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bindingPoint_Label = QtWidgets.QLabel(self.frame_4)
        self.bindingPoint_Label.setObjectName("bindingPoint_Label")
        self.horizontalLayout_6.addWidget(self.bindingPoint_Label, 0, QtCore.Qt.AlignLeft)
        self.x_Label = QtWidgets.QLabel(self.frame_4)
        self.x_Label.setObjectName("x_Label")
        self.horizontalLayout_6.addWidget(self.x_Label, 0, QtCore.Qt.AlignLeft)
        self.x_coord_LineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.x_coord_LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.x_coord_LineEdit.setObjectName("x_coord_LineEdit")
        self.horizontalLayout_6.addWidget(self.x_coord_LineEdit, 0, QtCore.Qt.AlignLeft)
        self.y_Label = QtWidgets.QLabel(self.frame_4)
        self.y_Label.setObjectName("y_Label")
        self.horizontalLayout_6.addWidget(self.y_Label, 0, QtCore.Qt.AlignLeft)
        self.y_coord_LineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.y_coord_LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.y_coord_LineEdit.setObjectName("y_coord_LineEdit")
        self.horizontalLayout_6.addWidget(self.y_coord_LineEdit, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.peekFromMap_PushButton = QtWidgets.QPushButton(self.frame_5)
        self.peekFromMap_PushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.peekFromMap_PushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.peekFromMap_PushButton.setText("")
        self.peekFromMap_PushButton.setCheckable(True)
        self.peekFromMap_PushButton.setObjectName("peekFromMap_PushButton")
        self.horizontalLayout_7.addWidget(self.peekFromMap_PushButton)
        self.peekFromGPSPushButton = QtWidgets.QPushButton(self.frame_5)
        self.peekFromGPSPushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.peekFromGPSPushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.peekFromGPSPushButton.setText("")
        self.peekFromGPSPushButton.setObjectName("peekFromGPSPushButton")
        self.horizontalLayout_7.addWidget(self.peekFromGPSPushButton)
        self.handTool_button = QtWidgets.QPushButton(self.frame_5)
        self.handTool_button.setMinimumSize(QtCore.QSize(25, 25))
        self.handTool_button.setMaximumSize(QtCore.QSize(25, 25))
        self.handTool_button.setText("")
        self.handTool_button.setObjectName("handTool_button")
        self.horizontalLayout_7.addWidget(self.handTool_button)
        self.movePoint_button = QtWidgets.QPushButton(self.frame_5)
        self.movePoint_button.setMinimumSize(QtCore.QSize(25, 25))
        self.movePoint_button.setMaximumSize(QtCore.QSize(25, 25))
        self.movePoint_button.setText("")
        self.movePoint_button.setObjectName("movePoint_button")
        self.horizontalLayout_7.addWidget(self.movePoint_button)
        self.manageLayers_button = QtWidgets.QPushButton(self.frame_5)
        self.manageLayers_button.setMinimumSize(QtCore.QSize(25, 25))
        self.manageLayers_button.setMaximumSize(QtCore.QSize(25, 25))
        self.manageLayers_button.setText("")
        self.manageLayers_button.setObjectName("manageLayers_button")
        self.horizontalLayout_7.addWidget(self.manageLayers_button)
        self.peekVydelFromMap_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.peekVydelFromMap_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.peekVydelFromMap_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.peekVydelFromMap_pushButton.setText("")
        self.peekVydelFromMap_pushButton.setCheckable(True)
        self.peekVydelFromMap_pushButton.setObjectName("peekVydelFromMap_pushButton")
        self.horizontalLayout_7.addWidget(self.peekVydelFromMap_pushButton)
        self.azimuthTool_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.azimuthTool_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.azimuthTool_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.azimuthTool_pushButton.setText("")
        self.azimuthTool_pushButton.setCheckable(True)
        self.azimuthTool_pushButton.setChecked(False)
        self.azimuthTool_pushButton.setObjectName("azimuthTool_pushButton")
        self.horizontalLayout_7.addWidget(self.azimuthTool_pushButton)
        self.lesoseka_from_map_button = QtWidgets.QPushButton(self.frame_5)
        self.lesoseka_from_map_button.setMinimumSize(QtCore.QSize(25, 25))
        self.lesoseka_from_map_button.setMaximumSize(QtCore.QSize(25, 25))
        self.lesoseka_from_map_button.setText("")
        self.lesoseka_from_map_button.setCheckable(True)
        self.lesoseka_from_map_button.setObjectName("lesoseka_from_map_button")
        self.horizontalLayout_7.addWidget(self.lesoseka_from_map_button)
        self.lesoseka_from_map_points_button = QtWidgets.QPushButton(self.frame_5)
        self.lesoseka_from_map_points_button.setMinimumSize(QtCore.QSize(25, 25))
        self.lesoseka_from_map_points_button.setMaximumSize(QtCore.QSize(25, 25))
        self.lesoseka_from_map_points_button.setText("")
        self.lesoseka_from_map_points_button.setCheckable(True)
        self.lesoseka_from_map_points_button.setObjectName("lesoseka_from_map_points_button")
        self.horizontalLayout_7.addWidget(self.lesoseka_from_map_points_button)
        self.exportAsImage_PushButton = QtWidgets.QPushButton(self.frame_5)
        self.exportAsImage_PushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.exportAsImage_PushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.exportAsImage_PushButton.setText("")
        self.exportAsImage_PushButton.setCheckable(False)
        self.exportAsImage_PushButton.setObjectName("exportAsImage_PushButton")
        self.horizontalLayout_7.addWidget(self.exportAsImage_PushButton)
        self.buildLesoseka_Button = QtWidgets.QPushButton(self.frame_5)
        self.buildLesoseka_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.buildLesoseka_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.buildLesoseka_Button.setText("")
        self.buildLesoseka_Button.setObjectName("buildLesoseka_Button")
        self.horizontalLayout_7.addWidget(self.buildLesoseka_Button)
        self.editAttributes_button = QtWidgets.QPushButton(self.frame_5)
        self.editAttributes_button.setMinimumSize(QtCore.QSize(25, 25))
        self.editAttributes_button.setMaximumSize(QtCore.QSize(25, 25))
        self.editAttributes_button.setText("")
        self.editAttributes_button.setObjectName("editAttributes_button")
        self.horizontalLayout_7.addWidget(self.editAttributes_button)
        self.saveLesoseka_Button = QtWidgets.QPushButton(self.frame_5)
        self.saveLesoseka_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.saveLesoseka_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.saveLesoseka_Button.setText("")
        self.saveLesoseka_Button.setObjectName("saveLesoseka_Button")
        self.horizontalLayout_7.addWidget(self.saveLesoseka_Button)
        self.deleteLesoseka_Button = QtWidgets.QPushButton(self.frame_5)
        self.deleteLesoseka_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.deleteLesoseka_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteLesoseka_Button.setText("")
        self.deleteLesoseka_Button.setObjectName("deleteLesoseka_Button")
        self.horizontalLayout_7.addWidget(self.deleteLesoseka_Button)
        self.generateReport_Button = QtWidgets.QPushButton(self.frame_5)
        self.generateReport_Button.setMinimumSize(QtCore.QSize(25, 25))
        self.generateReport_Button.setMaximumSize(QtCore.QSize(25, 25))
        self.generateReport_Button.setText("")
        self.generateReport_Button.setObjectName("generateReport_Button")
        self.horizontalLayout_7.addWidget(self.generateReport_Button)
        self.horizontalLayout.addWidget(self.frame_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addNode_button = QtWidgets.QToolButton(self.frame_2)
        self.addNode_button.setMinimumSize(QtCore.QSize(25, 25))
        self.addNode_button.setMaximumSize(QtCore.QSize(25, 25))
        self.addNode_button.setObjectName("addNode_button")
        self.verticalLayout_3.addWidget(self.addNode_button)
        self.deleteNode_button = QtWidgets.QToolButton(self.frame_2)
        self.deleteNode_button.setMinimumSize(QtCore.QSize(25, 25))
        self.deleteNode_button.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteNode_button.setObjectName("deleteNode_button")
        self.verticalLayout_3.addWidget(self.deleteNode_button)
        self.saveData_pushButton = QtWidgets.QToolButton(self.frame_2)
        self.saveData_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.saveData_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.saveData_pushButton.setFont(font)
        self.saveData_pushButton.setText("")
        self.saveData_pushButton.setObjectName("saveData_pushButton")
        self.verticalLayout_3.addWidget(self.saveData_pushButton)
        self.loadData_pushButton = QtWidgets.QToolButton(self.frame_2)
        self.loadData_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.loadData_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.loadData_pushButton.setFont(font)
        self.loadData_pushButton.setText("")
        self.loadData_pushButton.setObjectName("loadData_pushButton")
        self.verticalLayout_3.addWidget(self.loadData_pushButton)
        self.clearNodes_button = QtWidgets.QPushButton(self.frame_2)
        self.clearNodes_button.setMinimumSize(QtCore.QSize(25, 25))
        self.clearNodes_button.setMaximumSize(QtCore.QSize(25, 25))
        self.clearNodes_button.setObjectName("clearNodes_button")
        self.verticalLayout_3.addWidget(self.clearNodes_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.coord_radio_button = QtWidgets.QRadioButton(self.frame)
        self.coord_radio_button.setObjectName("coord_radio_button")
        self.horizontalLayout_4.addWidget(self.coord_radio_button)
        self.azimuth_radio_button = QtWidgets.QRadioButton(self.frame)
        self.azimuth_radio_button.setObjectName("azimuth_radio_button")
        self.horizontalLayout_4.addWidget(self.azimuth_radio_button)
        self.rumb_radio_button = QtWidgets.QRadioButton(self.frame)
        self.rumb_radio_button.setObjectName("rumb_radio_button")
        self.horizontalLayout_4.addWidget(self.rumb_radio_button)
        self.left_angle_radio_button = QtWidgets.QRadioButton(self.frame)
        self.left_angle_radio_button.setObjectName("left_angle_radio_button")
        self.horizontalLayout_4.addWidget(self.left_angle_radio_button)
        self.right_angle_radio_button = QtWidgets.QRadioButton(self.frame)
        self.right_angle_radio_button.setObjectName("right_angle_radio_button")
        self.horizontalLayout_4.addWidget(self.right_angle_radio_button)
        self.horizontalLayout_9.addWidget(self.frame)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.switchPadLayout = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.switchPadLayout.setObjectName("switchPadLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_3.setObjectName("label_3")
        self.switchPadLayout.addWidget(self.label_3)
        self.switchLayout = QtWidgets.QHBoxLayout()
        self.switchLayout.setObjectName("switchLayout")
        self.switchPadLayout.addLayout(self.switchLayout)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_2.setObjectName("label_2")
        self.switchPadLayout.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.horizontalFrame_4)
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outputLabel.setFont(font)
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_3.addWidget(self.outputLabel, 0, QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.canvas_scale_combo = QtWidgets.QComboBox(self.frame_6)
        self.canvas_scale_combo.setObjectName("canvas_scale_combo")
        self.verticalLayout_5.addWidget(self.canvas_scale_combo)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sliderLabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.sliderLabel.setFont(font)
        self.sliderLabel.setObjectName("sliderLabel")
        self.horizontalLayout_5.addWidget(self.sliderLabel, 0, QtCore.Qt.AlignRight)
        self.inclinationSlider = QtWidgets.QSlider(self.frame_3)
        self.inclinationSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.inclinationSlider.setMaximumSize(QtCore.QSize(10, 16777215))
        self.inclinationSlider.setSizeIncrement(QtCore.QSize(100, 0))
        self.inclinationSlider.setMinimum(-200)
        self.inclinationSlider.setMaximum(200)
        self.inclinationSlider.setSingleStep(1)
        self.inclinationSlider.setPageStep(5)
        self.inclinationSlider.setProperty("value", 0)
        self.inclinationSlider.setSliderPosition(0)
        self.inclinationSlider.setTracking(False)
        self.inclinationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.inclinationSlider.setInvertedAppearance(False)
        self.inclinationSlider.setInvertedControls(False)
        self.inclinationSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.inclinationSlider.setTickInterval(100)
        self.inclinationSlider.setObjectName("inclinationSlider")
        self.horizontalLayout_5.addWidget(self.inclinationSlider)
        self.magneticDeclination_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.magneticDeclination_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.magneticDeclination_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.magneticDeclination_pushButton.setText("")
        self.magneticDeclination_pushButton.setObjectName("magneticDeclination_pushButton")
        self.horizontalLayout_5.addWidget(self.magneticDeclination_pushButton)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.saveData_action = QtWidgets.QAction(MainWindow)
        self.saveData_action.setObjectName("saveData_action")
        self.loadData_action = QtWidgets.QAction(MainWindow)
        self.loadData_action.setObjectName("loadData_action")
        self.csvExport_action = QtWidgets.QAction(MainWindow)
        self.csvExport_action.setObjectName("csvExport_action")
        self.menu.addAction(self.saveData_action)
        self.menu.addAction(self.loadData_action)
        self.menu.addAction(self.csvExport_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ГисЛес для QGIS"))
        self.bindingPoint_Label.setText(_translate("MainWindow", "Точка привязки:"))
        self.x_Label.setText(_translate("MainWindow", "N:"))
        self.y_Label.setText(_translate("MainWindow", "E:"))
        self.peekFromMap_PushButton.setToolTip(_translate("MainWindow", "Выбрать точку на карте (Ctrl+Q)"))
        self.peekFromGPSPushButton.setToolTip(_translate("MainWindow", "Точка привязки по GPS"))
        self.handTool_button.setToolTip(_translate("MainWindow", "Навигация по карте (Ctrl+H)"))
        self.manageLayers_button.setToolTip(_translate("MainWindow", "Настроить видимость слоев (Ctrl+L)"))
        self.peekVydelFromMap_pushButton.setToolTip(_translate("MainWindow", "Загрузить данные лесосеки"))
        self.azimuthTool_pushButton.setToolTip(_translate("MainWindow", "Измерение расстояния и азимута (Ctrl+A)"))
        self.lesoseka_from_map_button.setToolTip(_translate("MainWindow", "Вынос по границам выдела (Ctrl+W)"))
        self.lesoseka_from_map_points_button.setToolTip(_translate("MainWindow", "Вынос по произвольным точкам (Ctrl+E)"))
        self.exportAsImage_PushButton.setToolTip(_translate("MainWindow", "Экспортировать как изображение"))
        self.buildLesoseka_Button.setToolTip(_translate("MainWindow", "Построить лесосеку (Ctrl+B)"))
        self.editAttributes_button.setToolTip(_translate("MainWindow", "Редактировать атрибуты"))
        self.saveLesoseka_Button.setToolTip(_translate("MainWindow", "Сохранить лесосеку"))
        self.deleteLesoseka_Button.setToolTip(_translate("MainWindow", "Удалить лесосеку"))
        self.generateReport_Button.setToolTip(_translate("MainWindow", "Сформировать отчет"))
        self.addNode_button.setToolTip(_translate("MainWindow", "Добавить точку (Ctrl + +)"))
        self.addNode_button.setText(_translate("MainWindow", "+"))
        self.deleteNode_button.setToolTip(_translate("MainWindow", "Удалить последнюю точку (Ctrl + -)"))
        self.deleteNode_button.setText(_translate("MainWindow", "-"))
        self.saveData_pushButton.setToolTip(_translate("MainWindow", "Сохранить данные отвода в файл (Ctrl + S)"))
        self.loadData_pushButton.setToolTip(_translate("MainWindow", "Загрузить данные из файла (Ctrl + O)"))
        self.clearNodes_button.setToolTip(_translate("MainWindow", "Удалить все узлы"))
        self.clearNodes_button.setText(_translate("MainWindow", "✕"))
        self.coord_radio_button.setToolTip(_translate("MainWindow", "Координаты (Ctrl+1)"))
        self.coord_radio_button.setText(_translate("MainWindow", "КРД"))
        self.azimuth_radio_button.setToolTip(_translate("MainWindow", "Азимуты (Ctrl+2)"))
        self.azimuth_radio_button.setText(_translate("MainWindow", "АЗТ"))
        self.rumb_radio_button.setToolTip(_translate("MainWindow", "Румбы (Ctrl+3)"))
        self.rumb_radio_button.setText(_translate("MainWindow", "РМБ"))
        self.left_angle_radio_button.setToolTip(_translate("MainWindow", "Левые внутренние углы (Ctrl+4)"))
        self.left_angle_radio_button.setText(_translate("MainWindow", "ЛВУ"))
        self.right_angle_radio_button.setToolTip(_translate("MainWindow", "Правые внутернние углы (Ctrl + 5)"))
        self.right_angle_radio_button.setText(_translate("MainWindow", "ПВУ"))
        self.label_3.setToolTip(_translate("MainWindow", "Decimal Degrees (Десятичный формат) (Ctrl+Shift+R)"))
        self.label_3.setText(_translate("MainWindow", "DD"))
        self.label_2.setToolTip(_translate("MainWindow", "Degrees Minutes Seconds (Градусы, Минуты, Секунды) (Ctrl+Shift+R)"))
        self.label_2.setText(_translate("MainWindow", "DMS"))
        self.sliderLabel.setText(_translate("MainWindow", "0"))
        self.inclinationSlider.setToolTip(_translate("MainWindow", "Магнитное склонение (Ctrl+Вниз/Вверх, Ctrl+Shift+Вниз/Вверх)"))
        self.magneticDeclination_pushButton.setToolTip(_translate("MainWindow", "Магнитное склонение по данным всемирной магнитной модели сервиса NOAA\n"
" Satellite and Information Service центра National Geophysical Data Center"))
        self.menu.setTitle(_translate("MainWindow", "Данные отвода"))
        self.saveData_action.setText(_translate("MainWindow", "Сохранить (Ctrl+S)"))
        self.loadData_action.setText(_translate("MainWindow", "Загрузить (Ctrl+O)"))
        self.csvExport_action.setText(_translate("MainWindow", "Экспорт в CSV"))

