# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NLK\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\trial_area\ui\areaControllerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(313, 466)
        Dialog.setWindowTitle("Управление лесосекой")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_pushButton = QtWidgets.QPushButton(Dialog)
        self.edit_pushButton.setCheckable(True)
        self.edit_pushButton.setObjectName("edit_pushButton")
        self.horizontalLayout.addWidget(self.edit_pushButton)
        self.count_pushButton = QtWidgets.QPushButton(Dialog)
        self.count_pushButton.setObjectName("count_pushButton")
        self.horizontalLayout.addWidget(self.count_pushButton)
        self.delete_pushButton = QtWidgets.QPushButton(Dialog)
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.horizontalLayout.addWidget(self.delete_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.gplho_comboBox = QtWidgets.QComboBox(Dialog)
        self.gplho_comboBox.setObjectName("gplho_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gplho_comboBox)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leshos_comboBox = QtWidgets.QComboBox(Dialog)
        self.leshos_comboBox.setObjectName("leshos_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leshos_comboBox)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lesnich_comboBox = QtWidgets.QComboBox(Dialog)
        self.lesnich_comboBox.setObjectName("lesnich_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lesnich_comboBox)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.num_kv_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.num_kv_lineEdit.setObjectName("num_kv_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.num_kv_lineEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.num_vd_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.num_vd_lineEdit.setObjectName("num_vd_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.num_vd_lineEdit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.area_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.area_lineEdit.setObjectName("area_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.area_lineEdit)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.num_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.num_lineEdit.setObjectName("num_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.num_lineEdit)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.useType_comboBox = QtWidgets.QComboBox(Dialog)
        self.useType_comboBox.setObjectName("useType_comboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.useType_comboBox)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cuttingType_comboBox = QtWidgets.QComboBox(Dialog)
        self.cuttingType_comboBox.setObjectName("cuttingType_comboBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cuttingType_comboBox)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fio_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.fio_lineEdit.setObjectName("fio_lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fio_lineEdit)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.info_textEdit = QtWidgets.QTextEdit(Dialog)
        self.info_textEdit.setObjectName("info_textEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.info_textEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.edit_pushButton.setText(_translate("Dialog", "Редактировать"))
        self.count_pushButton.setText(_translate("Dialog", "Перечет"))
        self.delete_pushButton.setText(_translate("Dialog", "Удалить"))
        self.label.setText(_translate("Dialog", "ГПЛХО/ Ведомство"))
        self.label_2.setText(_translate("Dialog", "Учреждение"))
        self.label_3.setText(_translate("Dialog", "Лесничество"))
        self.label_4.setText(_translate("Dialog", "Квартал"))
        self.label_5.setText(_translate("Dialog", "Выдел (а)"))
        self.label_6.setText(_translate("Dialog", "Площадь"))
        self.label_7.setText(_translate("Dialog", "Номер лесосеки"))
        self.label_8.setText(_translate("Dialog", "Пользование"))
        self.label_9.setText(_translate("Dialog", "Вид рубки"))
        self.label_10.setText(_translate("Dialog", "Исполнитель"))
        self.label_11.setText(_translate("Dialog", "Дата"))
        self.label_12.setText(_translate("Dialog", "Дополнительно"))

