# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NLK\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\trial_area\ui\filterAreaWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tools(object):
    def setupUi(self, Tools):
        Tools.setObjectName("Tools")
        Tools.resize(491, 580)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setObjectName("tabWidget")
        self.FilterAreaPanel = QtWidgets.QWidget()
        self.FilterAreaPanel.setObjectName("FilterAreaPanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FilterAreaPanel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lesnich_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.lesnich_comboBox.setEnabled(True)
        self.lesnich_comboBox.setEditable(True)
        self.lesnich_comboBox.setObjectName("lesnich_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lesnich_comboBox)
        self.label_13 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.num_kv_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.num_kv_comboBox.setEditable(True)
        self.num_kv_comboBox.setObjectName("num_kv_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.num_kv_comboBox)
        self.label_14 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.num_vd_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.num_vd_comboBox.setEditable(True)
        self.num_vd_comboBox.setObjectName("num_vd_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.num_vd_comboBox)
        self.label_15 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.area_min = QtWidgets.QLineEdit(self.FilterAreaPanel)
        self.area_min.setObjectName("area_min")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.area_min)
        self.label_16 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.area_max = QtWidgets.QLineEdit(self.FilterAreaPanel)
        self.area_max.setObjectName("area_max")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.area_max)
        self.label_17 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.num_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.num_comboBox.setEditable(True)
        self.num_comboBox.setObjectName("num_comboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.num_comboBox)
        self.label_18 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.useType_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.useType_comboBox.setEditable(True)
        self.useType_comboBox.setObjectName("useType_comboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.useType_comboBox)
        self.label_19 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cuttingType_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.cuttingType_comboBox.setEditable(True)
        self.cuttingType_comboBox.setObjectName("cuttingType_comboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cuttingType_comboBox)
        self.label_20 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.fio_comboBox = QtWidgets.QComboBox(self.FilterAreaPanel)
        self.fio_comboBox.setEditable(True)
        self.fio_comboBox.setObjectName("fio_comboBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fio_comboBox)
        self.label_21 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.date_lineEdit = QtWidgets.QLineEdit(self.FilterAreaPanel)
        self.date_lineEdit.setObjectName("date_lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.date_lineEdit)
        self.label_22 = QtWidgets.QLabel(self.FilterAreaPanel)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.info = QtWidgets.QLineEdit(self.FilterAreaPanel)
        self.info.setObjectName("info")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.info)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.prev_pushButton = QtWidgets.QPushButton(self.FilterAreaPanel)
        self.prev_pushButton.setObjectName("prev_pushButton")
        self.gridLayout.addWidget(self.prev_pushButton, 0, 0, 1, 1)
        self.clear_pushButton = QtWidgets.QPushButton(self.FilterAreaPanel)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 0, 4, 1, 1)
        self.filter_pushButton = QtWidgets.QPushButton(self.FilterAreaPanel)
        self.filter_pushButton.setObjectName("filter_pushButton")
        self.gridLayout.addWidget(self.filter_pushButton, 0, 3, 1, 1)
        self.export_pushButton = QtWidgets.QPushButton(self.FilterAreaPanel)
        self.export_pushButton.setObjectName("export_pushButton")
        self.gridLayout.addWidget(self.export_pushButton, 0, 5, 1, 1)
        self.areaCounter_lineEdit = QtWidgets.QLabel(self.FilterAreaPanel)
        self.areaCounter_lineEdit.setText("")
        self.areaCounter_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.areaCounter_lineEdit.setObjectName("areaCounter_lineEdit")
        self.gridLayout.addWidget(self.areaCounter_lineEdit, 0, 2, 1, 1)
        self.next_pushButton = QtWidgets.QPushButton(self.FilterAreaPanel)
        self.next_pushButton.setObjectName("next_pushButton")
        self.gridLayout.addWidget(self.next_pushButton, 0, 1, 1, 1)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.areaInfo_textEdit = QtWidgets.QTextEdit(self.FilterAreaPanel)
        self.areaInfo_textEdit.setReadOnly(True)
        self.areaInfo_textEdit.setObjectName("areaInfo_textEdit")
        self.verticalLayout_3.addWidget(self.areaInfo_textEdit)
        self.tabWidget.addTab(self.FilterAreaPanel, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Tools.setWidget(self.dockWidgetContents)

        self.retranslateUi(Tools)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Tools)

    def retranslateUi(self, Tools):
        _translate = QtCore.QCoreApplication.translate
        Tools.setWindowTitle(_translate("Tools", "Инструменты"))
        self.label_12.setText(_translate("Tools", "Лесничество"))
        self.label_13.setText(_translate("Tools", "Квартал"))
        self.label_14.setText(_translate("Tools", "Выдел"))
        self.label_15.setText(_translate("Tools", "Площадь от"))
        self.label_16.setText(_translate("Tools", "до"))
        self.label_17.setText(_translate("Tools", "Номер лесосеки"))
        self.label_18.setText(_translate("Tools", "Пользование"))
        self.label_19.setText(_translate("Tools", "Вид рубки"))
        self.label_20.setText(_translate("Tools", "Исполнитель"))
        self.label_21.setText(_translate("Tools", "Дата"))
        self.label_22.setText(_translate("Tools", "Дополнительно"))
        self.prev_pushButton.setText(_translate("Tools", "<"))
        self.clear_pushButton.setText(_translate("Tools", "Очистить"))
        self.filter_pushButton.setText(_translate("Tools", "Выделить"))
        self.export_pushButton.setText(_translate("Tools", "Экспортировать"))
        self.next_pushButton.setText(_translate("Tools", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterAreaPanel), _translate("Tools", "Фильтр лесосек"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Tools", "Tab 2"))

