# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\OSGeo4W64\apps\qgis\python\plugins\QgsLes\ui\settingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(380, 255)
        self.buttonBox = QtWidgets.QDialogButtonBox(settingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 220, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.settingsWidget = QtWidgets.QTabWidget(settingsDialog)
        self.settingsWidget.setEnabled(True)
        self.settingsWidget.setGeometry(QtCore.QRect(10, 10, 351, 201))
        self.settingsWidget.setAutoFillBackground(False)
        self.settingsWidget.setObjectName("settingsWidget")
        self.otvodSettings = QtWidgets.QWidget()
        self.otvodSettings.setObjectName("otvodSettings")
        self.reportLabel = QtWidgets.QLabel(self.otvodSettings)
        self.reportLabel.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.reportLabel.setObjectName("reportLabel")
        self.lineEdit = QtWidgets.QLineEdit(self.otvodSettings)
        self.lineEdit.setGeometry(QtCore.QRect(120, 20, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.otvodSettings)
        self.toolButton.setGeometry(QtCore.QRect(314, 20, 21, 20))
        self.toolButton.setObjectName("toolButton")
        self.saveOtvodSettingsButton = QtWidgets.QPushButton(self.otvodSettings)
        self.saveOtvodSettingsButton.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.saveOtvodSettingsButton.setObjectName("saveOtvodSettingsButton")
        self.label = QtWidgets.QLabel(self.otvodSettings)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.otvodSettings)
        self.comboBox.setGeometry(QtCore.QRect(120, 60, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.otvodSettings)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.otvodSettings)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 100, 211, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.settingsWidget.addTab(self.otvodSettings, "")
        self.mdolSettings = QtWidgets.QWidget()
        self.mdolSettings.setObjectName("mdolSettings")
        self.label_3 = QtWidgets.QLabel(self.mdolSettings)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.mdolSettings)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 20, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.mdolSettings)
        self.toolButton_2.setGeometry(QtCore.QRect(310, 20, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.settingsWidget.addTab(self.mdolSettings, "")
        self.bdSettings = QtWidgets.QWidget()
        self.bdSettings.setObjectName("bdSettings")
        self.hostLabel = QtWidgets.QLabel(self.bdSettings)
        self.hostLabel.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.hostLabel.setObjectName("hostLabel")
        self.portLabel = QtWidgets.QLabel(self.bdSettings)
        self.portLabel.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.portLabel.setObjectName("portLabel")
        self.connectionLineEdit = QtWidgets.QLineEdit(self.bdSettings)
        self.connectionLineEdit.setGeometry(QtCore.QRect(120, 20, 211, 20))
        self.connectionLineEdit.setObjectName("connectionLineEdit")
        self.usernameLabel = QtWidgets.QLabel(self.bdSettings)
        self.usernameLabel.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.bdSettings)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.passwordLabel.setObjectName("passwordLabel")
        self.portLineEdit = QtWidgets.QLineEdit(self.bdSettings)
        self.portLineEdit.setGeometry(QtCore.QRect(120, 50, 41, 20))
        self.portLineEdit.setObjectName("portLineEdit")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.bdSettings)
        self.usernameLineEdit.setGeometry(QtCore.QRect(120, 80, 211, 20))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.bdSettings)
        self.passwordLineEdit.setGeometry(QtCore.QRect(120, 110, 211, 20))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.saveConfigButton = QtWidgets.QPushButton(self.bdSettings)
        self.saveConfigButton.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.saveConfigButton.setCheckable(False)
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.testDBConnection_pushButton = QtWidgets.QPushButton(self.bdSettings)
        self.testDBConnection_pushButton.setGeometry(QtCore.QRect(14, 140, 241, 23))
        self.testDBConnection_pushButton.setObjectName("testDBConnection_pushButton")
        self.BDNameLabel = QtWidgets.QLabel(self.bdSettings)
        self.BDNameLabel.setGeometry(QtCore.QRect(170, 50, 47, 13))
        self.BDNameLabel.setObjectName("BDNameLabel")
        self.BDNameLineEdit = QtWidgets.QLineEdit(self.bdSettings)
        self.BDNameLineEdit.setGeometry(QtCore.QRect(210, 50, 121, 20))
        self.BDNameLineEdit.setObjectName("BDNameLineEdit")
        self.settingsWidget.addTab(self.bdSettings, "")
        self.btSettings = QtWidgets.QWidget()
        self.btSettings.setObjectName("btSettings")
        self.fork_label = QtWidgets.QLabel(self.btSettings)
        self.fork_label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.fork_label.setObjectName("fork_label")
        self.rangeFinder_label = QtWidgets.QLabel(self.btSettings)
        self.rangeFinder_label.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.rangeFinder_label.setObjectName("rangeFinder_label")
        self.SaveBTConfigPushButton = QtWidgets.QPushButton(self.btSettings)
        self.SaveBTConfigPushButton.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.SaveBTConfigPushButton.setObjectName("SaveBTConfigPushButton")
        self.changeForkComButton = QtWidgets.QToolButton(self.btSettings)
        self.changeForkComButton.setGeometry(QtCore.QRect(294, 20, 41, 20))
        self.changeForkComButton.setCheckable(False)
        self.changeForkComButton.setAutoExclusive(False)
        self.changeForkComButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.changeForkComButton.setAutoRaise(False)
        self.changeForkComButton.setArrowType(QtCore.Qt.NoArrow)
        self.changeForkComButton.setObjectName("changeForkComButton")
        self.changeRangeFinderComButton = QtWidgets.QToolButton(self.btSettings)
        self.changeRangeFinderComButton.setGeometry(QtCore.QRect(294, 60, 41, 20))
        self.changeRangeFinderComButton.setObjectName("changeRangeFinderComButton")
        self.forkComPortlineEdit = QtWidgets.QLineEdit(self.btSettings)
        self.forkComPortlineEdit.setEnabled(False)
        self.forkComPortlineEdit.setGeometry(QtCore.QRect(130, 20, 151, 20))
        self.forkComPortlineEdit.setReadOnly(True)
        self.forkComPortlineEdit.setObjectName("forkComPortlineEdit")
        self.rangeFinderLineEdit = QtWidgets.QLineEdit(self.btSettings)
        self.rangeFinderLineEdit.setEnabled(False)
        self.rangeFinderLineEdit.setGeometry(QtCore.QRect(130, 60, 151, 20))
        self.rangeFinderLineEdit.setReadOnly(True)
        self.rangeFinderLineEdit.setObjectName("rangeFinderLineEdit")
        self.settingsWidget.addTab(self.btSettings, "")

        self.retranslateUi(settingsDialog)
        self.settingsWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(settingsDialog.accept)
        self.buttonBox.rejected.connect(settingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Настройки QgsLes"))
        self.reportLabel.setText(_translate("settingsDialog", "Путь к отчету"))
        self.toolButton.setText(_translate("settingsDialog", "..."))
        self.saveOtvodSettingsButton.setText(_translate("settingsDialog", "Сохранить"))
        self.label.setText(_translate("settingsDialog", "Формат координат по умолчанию"))
        self.label_2.setText(_translate("settingsDialog", "Формат ввода по умолчанию"))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.otvodSettings), _translate("settingsDialog", "Отвод лесосек"))
        self.label_3.setText(_translate("settingsDialog", "Путь к ведомости"))
        self.toolButton_2.setText(_translate("settingsDialog", "..."))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.mdolSettings), _translate("settingsDialog", "МДОЛ"))
        self.hostLabel.setText(_translate("settingsDialog", "Адрес соединения"))
        self.portLabel.setText(_translate("settingsDialog", "Порт"))
        self.usernameLabel.setText(_translate("settingsDialog", "Имя пользователя"))
        self.passwordLabel.setText(_translate("settingsDialog", "Пароль"))
        self.saveConfigButton.setText(_translate("settingsDialog", "Сохранить"))
        self.testDBConnection_pushButton.setText(_translate("settingsDialog", "Тест соединения"))
        self.BDNameLabel.setText(_translate("settingsDialog", "Имя БД"))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.bdSettings), _translate("settingsDialog", "База данных"))
        self.fork_label.setText(_translate("settingsDialog", "Мерная вилка"))
        self.rangeFinder_label.setText(_translate("settingsDialog", "Дальномер"))
        self.SaveBTConfigPushButton.setText(_translate("settingsDialog", "Сохранить"))
        self.changeForkComButton.setText(_translate("settingsDialog", "Edit..."))
        self.changeRangeFinderComButton.setText(_translate("settingsDialog", "Edit..."))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.btSettings), _translate("settingsDialog", "Bluetooth"))


